package entities

type TerritoryName string

const (
	Afghanistan         TerritoryName = "AFGHANISTAN"
	Alaska              TerritoryName = "ALASKA"
	Alberta             TerritoryName = "ALBERTA"
	Argentina           TerritoryName = "ARGENTINA"
	Brazil              TerritoryName = "BRAZIL"
	CentralAfrica       TerritoryName = "CENTRAL_AFRICA"
	CentralAmerica      TerritoryName = "CENTRAL_AMERICA"
	China               TerritoryName = "CHINA"
	EastAfrica          TerritoryName = "EAST_AFRICA"
	EasternAustralia    TerritoryName = "EASTERN_AUSTRALIA"
	EasternCanada       TerritoryName = "EASTERN_CANADA"
	EasternUnitedStates TerritoryName = "EASTERN_UNITED_STATES"
	Egypt               TerritoryName = "EGYPT"
	GreatBritain        TerritoryName = "GREAT_BRITAIN"
	Greenland           TerritoryName = "GREENLAND"
	Iceland             TerritoryName = "ICELAND"
	India               TerritoryName = "INDIA"
	Irkutsk             TerritoryName = "IRKUTSK"
	Japan               TerritoryName = "JAPAN"
	Kamchatka           TerritoryName = "KAMCHATKA"
	Madagascar          TerritoryName = "MADAGASCAR"
	MiddleEast          TerritoryName = "MIDDLE_EAST"
	Mongolia            TerritoryName = "MONGOLIA"
	NewGuinea           TerritoryName = "NEW_GUINEA"
	NorthernEurope      TerritoryName = "NORTHERN_EUROPE"
	NorthwestTerritory  TerritoryName = "NORTHWEST_TERRITORY"
	NorthAfrica         TerritoryName = "NORTH_AFRICA"
	Ontario             TerritoryName = "ONTARIO"
	Peru                TerritoryName = "PERU"
	Russia              TerritoryName = "RUSSIA"
	Scandinavia         TerritoryName = "SCANDINAVIA"
	Siberia             TerritoryName = "SIBERIA"
	SoutheastAsia       TerritoryName = "SOUTHEAST_ASIA"
	SouthernEurope      TerritoryName = "SOUTHERN_EUROPE"
	SouthAfrica         TerritoryName = "SOUTH_AFRICA"
	Ural                TerritoryName = "URAL"
	Venezuela           TerritoryName = "VENEZUELA"
	WesternAustralia    TerritoryName = "WESTERN_AUSTRALIA"
	WesternEurope       TerritoryName = "WESTERN_EUROPE"
	WesternUnitedStates TerritoryName = "WESTERN_UNITED_STATES"
	Yakutsk             TerritoryName = "YAKUTSK"
)
